sonar.projectKey=need4deed
sonar.projectName=need4deed
sonar.host.url=http://localhost:9001

sonar.login=<token>

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

